### ISSUE TITLE
setup.py requires `requests` library 

### ISSUE THREAD

**Issue by dkiser** [rbw0/pysnow#1]
https://github.com/rbw0/pysnow/blob/master/setup.py#L69 pulls in `requests` as a pre-req and thus causes a chicken and the egg problem.

Please break out version into its own module that doesn't rely on an import path for `requests`.  This should allow users to freshly install package.

**Comment by rbw0** [comment]
Hello,

Thank you for reporting this.
Fixed in 2b5d732 

I'll release it along with some tests in a couple of days.
