### ISSUE TITLE
requests lib verify option not available

### ISSUE THREAD

**Issue by ryanback** [rbw0/pysnow#32]
In our development environment, our SSL certs are not valid.  I do not see a way in pysnow to pass along verify=False.  I would recommend passing kwargs through to the requests init.  Any reason why there is no customization around that?

**Comment by rbw0** [comment]
Hello!

You can pass a `requests.Session` object to `pysnow.Client` as of version 0.4.0.

Try this:

```python
import pysnow
import requests

s = requests.Session()
s.verify = False
s.auth = requests.auth.HTTPBasicAuth('<user>', '<pass>')
s = pysnow.Client(instance='instance', session=s)
...
```

Regards,
Robert

**Comment by ryanback** [comment]
Awesome, thank you!
