### ISSUE TITLE
insertMultiple records supported?

### ISSUE THREAD

**Issue by samrocketman** [rbw0/pysnow#57]
I'm able to dump many records and store them in a table.  I currently have a Python list of Records (each record having a unique `sys_id`).

Looking at the [ServiceNow API docs it looks like `insertMultiple`](https://docs.servicenow.com/bundle/helsinki-servicenow-platform/page/integrate/web-services-apis/reference/r_InsertMultiple.html) is supported.

Is that possible with the current version of this API client?  If not, this is a feature request :+1: .

Edit:  Looks like the [JSON API also supports `insertMultple`](http://wiki.servicenow.com/index.php?title=JSONv2_Web_Service#insert).

**Comment by samrocketman** [comment]
I'm thinking I can just use your `s.insert()` method and set the `payload` to:
```python
payload = {"records":[{"short_description":"this was inserted with python using JSON 1", "priority": "1 - Critical", "impact":"1", "caller_id":"Fred Luddy"},
            {"short_description":"this was inserted with python using JSON 2", "priority": "1 - Critical", "impact":"1", "caller_id":"Fred Luddy"}]}
```

**Comment by rbw0** [comment]
Absolutely, sounds like a good idea.

Can't find anything on this in the SN REST API docs, but it might be possible (passing an array of objects basically).
Should it lack the support, then we'll just implement this in insert(). Perhaps utilizing some async version of the requests library for larger bulk-inserts. And we'd probably need some good tracking of the responses.

Do you want to write it or should I?

**Comment by samrocketman** [comment]
It works as-is by passing in `{"records":[]}` as the payload.

**Comment by samrocketman** [comment]
Here's what I came up with: https://github.com/samrocketman/servicenow-servicecatalog-exporter/blob/sc-exporter-0.3/importer.py#L36-L55

**Comment by samrocketman** [comment]
Looks like it doesn't work.  The client returned HTTP 201 but the records were not created.

**Comment by rbw0** [comment]
That's too bad.

Adding insert_multiple() functionality to the API that basically just iterates over a list and calls insert() for each item sequentially would be kind of useless imo, as users can do this easily themselves.
However, implementing insert_multiple() with concurrency support would probably offer some value as it would make the process of bulk-inserts faster. A lot faster. But it would have to be compatible with Python 2 and 3, which I think would be a bit of a challenge.

I'm thinking something like `insert_multiple(data=list_of_dicts, concurrency=10)`
...that would return a list of results.

Not sure how sought-after this functionality is though (haven't received any requests about it previously), but I guess it could be worth looking into.

**Comment by samrocketman** [comment]
I'm going to try something else.  I'm going to try taking the JSON export and convert it to servicenow XML so a user can simply upload one file.  Perhaps, if you know how, it would be nice to submit a payload with XML to an API endpoint and have it bulk update everything.  Don't worry about the formatting of the XML.  I already have that figured out.

See https://github.com/samrocketman/servicenow-servicecatalog-exporter/issues/1

**Comment by samrocketman** [comment]
Also, if you plan to use concurrency I highly recommend the eventlet library.

**Comment by rbw0** [comment]
I'll look into this when I'm back from vacation. Thanks

**Comment by rbw0** [comment]
I'll look into this when I'm back from vacation. Thanks

**Comment by rbw0** [comment]
I've looked into grequests and eventlet and decided not to implement this right now, as it adds too much complexity to core parts of pysnow.

**Comment by samrocketman** [comment]
Makes sense; I'm probably going to parallelize in my implementation.

**Comment by rupesh-arora-tm** [comment]
Well @rbw it will be great if you will provide this feature. Am also looking forward.
