### ISSUE TITLE
Response.all() does not return an empty iterator if the table is empty

### ISSUE THREAD

**Issue by siddweiker** [rbw0/pysnow#74]
Python 3.6.3
Querying an empty table with all() does not return an empty iterator. You can run this against the free dev instance:
```python
>>> data = client.resource(api_path='/table/cmdb_ci_storage_server').get(query={}).all()
>>> print([d for d in data])
[{}]
```

In some cases two empty dictionaries are returned.

**Comment by rbw0** [comment]
Hello,

I've created a branch with a fix for this in in 96aaccd53677a965e56fe720f58ca612afa5987b
I'd appreciate if you could test it, also, see if the issue with double dicts is gone (couldn't reproduce this).

Thanks

/Robert

**Comment by siddweiker** [comment]
Hey Robert,

I don't think that is the intended functionality. I would expect that when iterating over an empty result that it should behave similar to an empty list.
When I change that line 95 in resource.py to `pass` it seems to behave as such, but I'm not sure if that is the correct solution.

**Comment by rbw0** [comment]
Not that it makes a big difference in this particular scenario, but raising `StopIteration` here actually signals that there are no further values, which should make it behave just like an empty list.. just like `pass` or removing the empty result test altogether.

Some tests using StopIteration (same results as `pass` or removing the empty-test):

```python
# convert generator object to list
>>> print(list(response.all()))
[]

# convert to list and check length
>>> print(len(list(response.all())))
0

# list comprehension
>>> print([r for r in response.all()])
[]

```

If we want a list containing an empty dictionary here then raising `StopIteration` is definitely the right way to go imo.. however, I don't think that's what we want.

So, the best solution here is probably to remove the test altogether. Or what do you think?

**Comment by siddweiker** [comment]
Oh, maybe I did not test against the `StopIteration` version properly. Sorry about that. If it behaves like your code then that is perfect.

**Comment by siddweiker** [comment]
I properly tested this commit, and it fixes the issue. Thanks again.

**Comment by rbw0** [comment]
Fixed. The new version is available on pypi.

**Comment by siddweiker** [comment]
Quick addendum to this; based on [PEP 479](https://www.python.org/dev/peps/pep-0479/) the `StopIteration` is deprecated in python 3.5 in favor of `return`. The error I received before was actually a warning, apologies for the confusion.
```
DeprecationWarning: generator 'Response._parse_response' raised StopIteration
```

**Comment by rbw0** [comment]
@siddweiker Ah, yes.. you're right. Simply using `return` (without a value) should be compatible with both python 2 and 3.

I'll have this fixed in the next version.

Thanks :)
