### ISSUE TITLE
ModuleNotFoundError: No module named 'session'

### ISSUE THREAD

**Issue by kglg94** [rbw0/pysnow#78]
![image](https://user-images.githubusercontent.com/35241743/34697662-b76a884c-f499-11e7-8d6c-ee34694a901a.png)

**Comment by rbw0** [comment]
Hello!

Are you trying to `import session` like in the usage examples here?:
http://pysnow.readthedocs.io/en/latest/full_examples/oauth_client.html

Pysnow doesn't have a module called `session`, this was just an (fictive) example. You'll need to implement the actual storage yourself. The token can be stored in a database, session, file or whatever you wish.

Does that make sense? Let me know if you need any help.

Regards,
Robert

**Comment by rbw0** [comment]
I'll update the docs in the next version to clarify this.

**Comment by navyasomepalli** [comment]
Yes, I was trying to use the example but kept getting that error. So, What should I do now to get rid of that.

**Comment by rbw0** [comment]
I've updated the OAuth example here:
http://pysnow.readthedocs.io/en/latest/full_examples/oauth_client.html

Grab that code, set the instance name and credentials and you should be good to go.

Note that this code doesn't provide any persistence mechanism, the `store` here is just a basic dict. This means `OAuthClient.generate_token` will be called every time you execute this code, which introduces a significant overhead.
 
So..  `store` here should be changed to a real store of your application / script (this could be a database, session, file or whatever you like).

**Comment by kglg94** [comment]
Thank You:)
