### ISSUE TITLE
sysparams not passed when making call to a table.

### ISSUE THREAD

**Issue by klainn** [rbw0/pysnow#80]
I have a function
`    def connect_to_instance(self, instance_name, username, password):
        c = pysnow.Client(instance=instance_name, user=username, password=password)
        c.parameters.add_custom({'sysparm_display_value': 'True', 'sysparm_exclude_reference_link': 'True'})
        return c
`

My querybuilder query:
`
(pysnow.QueryBuilder().field('assignment_group').equals(['https://my_instance.service-now.com/api/now/table/sys_user_group/my_group_value', 'my_group_value']).AND().field('state').not_equals('100'))
`

I get results back from service now, foreign key relationships are followed and I get the values I expect.

But when I try to query with the foreign key values and not the values from the actual change table:
`
(pysnow.QueryBuilder().field('assignment_group').equals('MY-SWEET-GROUP').AND().field('state').equals('Closed'))
`
I get no results back.

Is there another place I need to set the client parameters?

**Comment by rbw0** [comment]
Hello klainn,

You don't need to set `sysparm_display_value` to True in order to query by display value -- it's only used to resolve referenced fields.

If you want to query a referenced field by value instead of ID, simply use "field_name.display_value" e.g:

```python
QueryBuilder().field('assignment_group.display_value').equals(['this_value', 'or_that_value'])
```
- Note here that passing a `list` to `equals()` actually performs an `IN` query.



Does this fix your issue? Sorry if I misunderstood something.


Another thing - the most common sysparms can be set directly, example:

```python
incident = c.resource(api_path='/table/incident')
incident.parameters.display_value = True
```
or if you want to set it globally:

```python
c = pysnow.Client(...)
c.parameters.display_value = True
```

Also, if you print the string representation of a `QueryBuilder` object, you get the "ServiceNow-interpretable" format of the query.

```python
>>> from pysnow import QueryBuilder
>>> str(QueryBuilder().field('test1').equals('hello').AND().field('test2').equals(['goodbye', 'hello']))
'test1=hello^test2INgoodbye,hello
```

**Comment by klainn** [comment]
Thanks for the great tips. I'm now getting results, but not those I expect.
I used your str(QueryBuilder()) and this is what it's passing to service now:

`assignment_group.display_value=MY-SWEET-GROUP^state.display_value!=Closed`

But the result set is:

Group: GROUP-1-GLB State: Closed
Group: GROUP-2-GLB State: Closed
Group: GROUP-3-GLB State: Closed
Group: GROUP-4-GLB State: Closed
Group: GROUP-5-GLB State: New
Group: GROUP-6-GLB State: Closed
Group: GROUP-7-GLB State: New

It's not limiting its results to MY-SWEET-GROUP.

My search string is now:
`(pysnow.QueryBuilder().field('assignment_group.display_value').equals('MY-SWEET-GROUP').AND().field('state.display_value').not_equals('Closed'))`

I have tried the display_value parameter here

`
    def ticket_lookup(self, conn_obj, api_path, query_obj):
        ticket_object = conn_obj.resource(api_path=api_path)
        ticket_object.parameters.display_value = True
        iterable_content = ticket_object.get(query=query_obj).all()
        return iterable_content
`

But I still get ALL results not just limited to my results.

**Comment by klainn** [comment]
Ah that helped out a bit.

`pysnow.QueryBuilder().field('assignment_group.name').equals('MY-SWEET-GROUP').AND().field('state.name').not_equals('Closed'))`

This limits my result set to MY-SWEET-GROUP but I'm getting incidents of all status.

Thanks much for the clarifications.

**Comment by rbw0** [comment]
Sure, no problem :)

Ah, all right. Yeah, those can be a little tricky.. and choices usually contain translations, so I'd recommend you to use ID instead (field('state').equals('7') for instance). This should be OK as choice IDs normally don't change, the labels however - you never knopw about those.

With that said... if you do want to get the state ID by name, you could do something like this:
```python
def get_incident_state_id(label):
    choices = c.resource(api_path='/table/sys_choice')
    states = choices.get(query={'label': label, 'name': 'incident'})
    state = states.first()
    return state['value']

state_id = get_incident_state_id('Closed')
```
