### ISSUE TITLE
[Feature] include 'link' attrib?

### ISSUE THREAD

**Issue by jcpunk** [rbw0/pysnow#87]
I use this mostly for CMDB queries.  It would be helpful if, when the returned item has 'sys_id' and 'link' is not defined for the object, the 'link' attrib is populated with a link back to the raw object via the API.

I'm not familiar with ObjectBuilder, so I'm not sure I could build this...

**Comment by rbw0** [comment]
Link as in a full URL to the record, like this?:
https://:instance.service-now.com/api/v1/:table/:sys_id

I don't know if tampering with the result is a good idea, but perhaps we could come up with some other solution to this. Could you provide some more details to why / when you need this?

**Comment by jcpunk** [comment]
Mostly I was just looking for a way to get the link quickly.

What do you think about having `str` return the link?

**Comment by rbw0** [comment]
String representation of the `Response` object? It's currently used for reporting status code and method used. And the convenience methods (one, first etc) are regular functions currently (but can become dict-like objects in the future if needed).

Perhaps a simple helper function would be a good way to accomplish this?

```python
from pysnow.helpers import get_record_link
...
record = response.one()

link = get_record_link(record)
```

What do you think?

**Comment by jcpunk** [comment]
That looks great

**Comment by rbw0** [comment]
I'll include this in 0.6.9

**Comment by rbw0** [comment]
1b64c050aa82b315404f2b56c417cb30702cbdb1

I've added this in the latest version, I made it a method of the Resource API.

Usage is simple:
```python
<...init..>
incident = c.resource(api_path='/table/incident')
<...some querying...>
link = incident.get_record_link(sys_id)
```
