### ISSUE TITLE
Ability to upload attachments using the Attachment API

### ISSUE THREAD

**Issue by ryancurrah** [rbw0/pysnow#9]
Would you be open to a Pull Request with an additional function in the Client class that uploads attachments? 

```bash
curl "https://dev00000.service-now.com/api/now/attachment/file?table_name=change_request&table_sys_id=414d1d584f072200745e3b728110c735&file_name=screenshot.png" \
--request POST \
--header "Accept:application/json" \
--user 'admin':'admin'
--header "Content-Type: "
-F "uploadFile=@screenshot.png" 
```

**Comment by rbw0** [comment]
Of course, go ahead :)

**Comment by rbw0** [comment]
Hello! Any progress on this? I could build this functionality (if you're not working on it).

**Comment by ryancurrah** [comment]
Yep I will try today to get a commit for you.

**Comment by ryancurrah** [comment]
PR https://github.com/rbw0/pysnow/pull/11 created, happy new year :)!
